/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package haskstuff-0.0.1 */
#ifndef VERSION_haskstuff
#define VERSION_haskstuff "0.0.1"
#endif /* VERSION_haskstuff */
#ifndef MIN_VERSION_haskstuff
#define MIN_VERSION_haskstuff(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_haskstuff */
/* package Cabal-3.6.3.0 */
#ifndef VERSION_Cabal
#define VERSION_Cabal "3.6.3.0"
#endif /* VERSION_Cabal */
#ifndef MIN_VERSION_Cabal
#define MIN_VERSION_Cabal(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  6 || \
  (major1) == 3 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_Cabal */
/* package array-0.5.4.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.4.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_array */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package binary-0.8.9.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.4.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.4.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 4)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.5.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.5.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_VERSION_containers */
/* package deepseq-1.4.6.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.6.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 6)
#endif /* MIN_VERSION_deepseq */
/* package directory-1.3.6.2 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.2"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */
/* package exceptions-0.10.4 */
#ifndef VERSION_exceptions
#define VERSION_exceptions "0.10.4"
#endif /* VERSION_exceptions */
#ifndef MIN_VERSION_exceptions
#define MIN_VERSION_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_exceptions */
/* package filepath-1.4.2.2 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.2"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */
/* package ghc-9.2.8 */
#ifndef VERSION_ghc
#define VERSION_ghc "9.2.8"
#endif /* VERSION_ghc */
#ifndef MIN_VERSION_ghc
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_ghc */
/* package ghc-boot-9.2.8 */
#ifndef VERSION_ghc_boot
#define VERSION_ghc_boot "9.2.8"
#endif /* VERSION_ghc_boot */
#ifndef MIN_VERSION_ghc_boot
#define MIN_VERSION_ghc_boot(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_ghc_boot */
/* package ghc-boot-th-9.2.8 */
#ifndef VERSION_ghc_boot_th
#define VERSION_ghc_boot_th "9.2.8"
#endif /* VERSION_ghc_boot_th */
#ifndef MIN_VERSION_ghc_boot_th
#define MIN_VERSION_ghc_boot_th(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_ghc_boot_th */
/* package ghc-compact-0.1.0.0 */
#ifndef VERSION_ghc_compact
#define VERSION_ghc_compact "0.1.0.0"
#endif /* VERSION_ghc_compact */
#ifndef MIN_VERSION_ghc_compact
#define MIN_VERSION_ghc_compact(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_ghc_compact */
/* package ghc-heap-9.2.8 */
#ifndef VERSION_ghc_heap
#define VERSION_ghc_heap "9.2.8"
#endif /* VERSION_ghc_heap */
#ifndef MIN_VERSION_ghc_heap
#define MIN_VERSION_ghc_heap(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_ghc_heap */
/* package ghc-prim-0.8.0 */
#ifndef VERSION_ghc_prim
#define VERSION_ghc_prim "0.8.0"
#endif /* VERSION_ghc_prim */
#ifndef MIN_VERSION_ghc_prim
#define MIN_VERSION_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_ghc_prim */
/* package ghci-9.2.8 */
#ifndef VERSION_ghci
#define VERSION_ghci "9.2.8"
#endif /* VERSION_ghci */
#ifndef MIN_VERSION_ghci
#define MIN_VERSION_ghci(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_ghci */
/* package haskeline-0.8.2.1 */
#ifndef VERSION_haskeline
#define VERSION_haskeline "0.8.2.1"
#endif /* VERSION_haskeline */
#ifndef MIN_VERSION_haskeline
#define MIN_VERSION_haskeline(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_haskeline */
/* package hpc-0.6.1.0 */
#ifndef VERSION_hpc
#define VERSION_hpc "0.6.1.0"
#endif /* VERSION_hpc */
#ifndef MIN_VERSION_hpc
#define MIN_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_hpc */
/* package integer-gmp-1.1 */
#ifndef VERSION_integer_gmp
#define VERSION_integer_gmp "1.1"
#endif /* VERSION_integer_gmp */
#ifndef MIN_VERSION_integer_gmp
#define MIN_VERSION_integer_gmp(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_integer_gmp */
/* package libiserv-9.2.8 */
#ifndef VERSION_libiserv
#define VERSION_libiserv "9.2.8"
#endif /* VERSION_libiserv */
#ifndef MIN_VERSION_libiserv
#define MIN_VERSION_libiserv(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_libiserv */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package parsec-3.1.15.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.15.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 15)
#endif /* MIN_VERSION_parsec */
/* package pretty-1.1.3.6 */
#ifndef VERSION_pretty
#define VERSION_pretty "1.1.3.6"
#endif /* VERSION_pretty */
#ifndef MIN_VERSION_pretty
#define MIN_VERSION_pretty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_pretty */
/* package process-1.6.16.0 */
#ifndef VERSION_process
#define VERSION_process "1.6.16.0"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 16)
#endif /* MIN_VERSION_process */
/* package rts-1.0.2 */
#ifndef VERSION_rts
#define VERSION_rts "1.0.2"
#endif /* VERSION_rts */
#ifndef MIN_VERSION_rts
#define MIN_VERSION_rts(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_rts */
/* package stm-2.5.0.2 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.0.2"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_stm */
/* package template-haskell-2.18.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.18.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package terminfo-0.4.1.5 */
#ifndef VERSION_terminfo
#define VERSION_terminfo "0.4.1.5"
#endif /* VERSION_terminfo */
#ifndef MIN_VERSION_terminfo
#define MIN_VERSION_terminfo(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_terminfo */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package time-1.11.1.1 */
#ifndef VERSION_time
#define VERSION_time "1.11.1.1"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  11 || \
  (major1) == 1 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_time */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package unix-2.7.2.2 */
#ifndef VERSION_unix
#define VERSION_unix "2.7.2.2"
#endif /* VERSION_unix */
#ifndef MIN_VERSION_unix
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 2)
#endif /* MIN_VERSION_unix */
/* package xhtml-3000.2.2.1 */
#ifndef VERSION_xhtml
#define VERSION_xhtml "3000.2.2.1"
#endif /* VERSION_xhtml */
#ifndef MIN_VERSION_xhtml
#define MIN_VERSION_xhtml(major1,major2,minor) (\
  (major1) <  3000 || \
  (major1) == 3000 && (major2) <  2 || \
  (major1) == 3000 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_xhtml */

/* tool gcc-13 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "13"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  0 || \
  (major1) == 13 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.8 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.8"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.8 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.8"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-1.8.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.2.8 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.8"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.42 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.42"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  42 || \
  (major1) == 2 && (major2) == 42 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "haskstuff-0.0.1-4KrCGm9HYhLJJ0O2519xHQ"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "haskstuff-0.0.1-4KrCGm9HYhLJJ0O2519xHQ"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
